---
title: "Tourism Data Analysis"
output:
  pdf_document: default
  html_document: default
date: "31 July 2019"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

library(tidyverse)
library(fpp2)
library(Matrix)
library(hts)
library(readr)
library(BigVAR)
library(vars)
library(tibble)
library(kableExtra)
library(reshape2)
```

Bias is estimated as the insample residual mean
```{r, echo=FALSE}
DF_BoxCoxTrans <- read.csv("DF_BoxCoxTrans.csv")[,-1]

DF_BoxCoxTrans %>% mutate(SquaredE = (`Actual` - `Forecasts`)^2) -> DF_BoxCoxTrans

DF_BoxCoxTrans %>% 
  group_by(`F.method`, `R.method`, Forecast_Horizon) %>% 
  summarise(MSE = round(mean(SquaredE)/1e3, digits = 2)) %>% 
  filter(Forecast_Horizon == 1) %>% 
  ungroup() %>% 
  dplyr::select(-Forecast_Horizon)-> Avg_MSE_h1

Avg_MSE_h1 %>% 
  mutate(F.method = recode(F.method, Unbiased_M1 = "Unbiased (Method 1)", 
                           Unbiased_M2 = "Unbiased (Method 2)")) %>% 
  spread(key = F.method, value = MSE) %>% 
  kable(format = "latex")
  
```

