---
title: "Tourism Data Analysis"
output:
  pdf_document: default
  html_document: default
date: "31 July 2019"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

library(tidyverse)
library(fpp2)
library(Matrix)
library(hts)
library(readr)
library(BigVAR)
library(vars)
library(tibble)
library(kableExtra)
library(reshape2)
```

Bias is estimated as the insample residual mean
```{r, echo=FALSE}
DF_1_50 <- read.csv("DF_1-50.csv")[,-1]
DF_51_100 <- read.csv("DF_51-100.csv")[,-1]
DF_101_140 <- read.csv("DF_101-140.csv")[,-1]

rbind(DF_1_50, DF_51_100, DF_101_140) %>% 
  as.data.frame() -> DF

DF %>% mutate(SquaredE = (`Actual` - `Forecasts`)^2) -> DF

DF %>% 
  group_by(`F.method`, `R.method`, Forecast_Horizon) %>% 
  summarise(MSE = mean(SquaredE)) -> Avg_MSE

Avg_MSE_tab1 <- Avg_MSE %>% dcast(`R.method` ~ Forecast_Horizon + `F.method`, value.var = "MSE") 

colnames(Avg_MSE_tab1) <- c("R.method", rep(c("Biased", "Unbiased"), 6))

Avg_MSE_tab1 %>% 
  kable(format = "latex") %>% 
  kableExtra::add_header_above(c(" " = 1, "h=1" = 2, "h=2" = 2, "h=3" = 2, "h=4" = 2,
                                 "h=5" = 2, "h=6" = 2)) 

```

