---
title: "Tourism Data Analysis"
output:
  pdf_document: 
    keep_tex: yes
  html_document: default
date: "Jan 2020"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

library(tidyverse)
library(Matrix)
library(hts)
library(readr)
library(tibble)
library(kableExtra)
library(tsutils)
# library(reshape2)
```



# Log Transformation with 100 observations of training window (ME and MSE calculated over 140 replications) 


```{r, echo=FALSE}
DF_LogTrans_WL100 <- read.csv("DF_LogTrans_WL100.csv")[,-1]

DF_LogTrans_WL100 <- DF_LogTrans_WL100 %>% 
  mutate(F.method=recode(F.method, `Bias` = 'Biased')) 
# so that we don't confuse Biased forecasts with ME

DF_LogTrans_WL100 %>% mutate(SquaredE = (`Actual` - `Forecasts`)^2) -> DF_LogTrans_WL100
DF_LogTrans_WL100 %>% mutate(ME = `Actual` - `Forecasts`) -> DF_LogTrans_WL100

# ME
DF_LogTrans_WL100 %>%  
  group_by(`F.method`, `R.method`, Forecast_Horizon) %>% 
  summarise(ME = sum(ME)/1e3) %>% 
  filter(Forecast_Horizon == 1) %>% 
  ungroup() %>% 
  dplyr::select(-Forecast_Horizon) -> Avg_Log_WL100_ME_h1

# New ME
DF_LogTrans_WL100 %>% 
  group_by(F.method, R.method, Series, Forecast_Horizon) %>% 
  summarise(ME = sum(ME)/1e3) %>%
  filter(Forecast_Horizon == 1) %>% 
  group_by(F.method,R.method) %>% 
  summarise(AME=sum(abs(ME))) %>% 
  ungroup() -> Avg_Log_WL100_ME_h1_new


Avg_Log_WL100_ME_h_new %>% 
  pivot_wider(names_from = c('F.method','R.method'),values_from =AME) %>%
  mutate_at(vars(`Biased_Bottom-up`:Unbiased_M1_OLS),funs(./Biased_Base)) %>% 
  mutate(Biased_Base=1) %>% 
  pivot_longer(cols = -Forecast_Horizon) %>% 
  pivot_wider(names_from = 'Forecast_Horizon')


# Make everything percentage improvement
Avg_Log_WL100_ME_h1 <- Avg_Log_WL100_ME_h1 %>% 
  mutate(ME=ME/Avg_Log_WL100_ME_h1[1,]$ME)

Avg_Log_WL100_ME_h1_new <- Avg_Log_WL100_ME_h1_new %>%
  mutate(AME=AME/Avg_Log_WL100_ME_h1_new[1,]$AME)

print("ME")
Avg_Log_WL100_ME_h1 %>% 
  mutate(F.method = recode(F.method, Unbiased_M1 = "Unbiased (Method 1)", 
                           Unbiased_M2 = "Unbiased (Method 2)")) %>% 
  spread(key = F.method, value = ME) %>% 
  kable(format = "latex",digits = 2)

print("New ME")
Avg_Log_WL100_ME_h1_new %>% 
  mutate(F.method = recode(F.method, Unbiased_M1 = "Unbiased (Method 1)", 
                           Unbiased_M2 = "Unbiased (Method 2)")) %>% 
  spread(key = F.method, value = AME) %>% 
  kable(format = "latex",digits = 2)

print("MSE")
DF_LogTrans_WL100 %>% 
  group_by(`F.method`, `R.method`, Forecast_Horizon) %>% 
  summarise(MSE = round(mean(SquaredE)/1e3, digits = 2)) %>% 
  filter(Forecast_Horizon == 1) %>% 
  ungroup() %>% 
  dplyr::select(-Forecast_Horizon)-> Avg_Log_WL100_MSE_h1


# Make everything percentage improvement
Avg_Log_WL100_MSE_h1 <- Avg_Log_WL100_MSE_h1 %>% 
  mutate(MSE=MSE/Avg_Log_WL100_MSE_h1[1,]$MSE)


Avg_Log_WL100_MSE_h1 %>% 
  mutate(F.method = recode(F.method, Unbiased_M1 = "Unbiased (Method 1)", 
                           Unbiased_M2 = "Unbiased (Method 2)")) %>% 
  spread(key = F.method, value = MSE) %>% 
  kable(format = "latex", digits = 2)

```

\newpage
# BoxCox Transformation for $\lambda \in (-0.5,2)$ with 100 observations of training window (ME and MSE calculated over 140 replications)


```{r, echo=FALSE}
DF_BoxCoxTrans_WL100 <- read.csv("DF_BoxCoxTrans_WL100.csv")[,-1]

DF_BoxCoxTrans_WL100 <- DF_BoxCoxTrans_WL100 %>% 
  mutate(F.method=recode(F.method, `Bias` = 'Biased')) 
# so that we don't confuse Biased forecasts with ME

DF_BoxCoxTrans_WL100 %>% mutate(SquaredE = (`Actual` - `Forecasts`)^2) -> DF_BoxCoxTrans_WL100
DF_BoxCoxTrans_WL100 %>% mutate(ME = `Actual` - `Forecasts`) -> DF_BoxCoxTrans_WL100

# ME
DF_BoxCoxTrans_WL100 %>% 
  group_by(`F.method`, `R.method`, Forecast_Horizon) %>% 
  summarise(ME = round(sum(ME)/1e3, digits = 2)) %>% 
  filter(Forecast_Horizon == 1) %>% 
  ungroup() %>% 
  dplyr::select(-Forecast_Horizon)-> Avg_BoxCox_WL100_ME_h1

# New ME
DF_BoxCoxTrans_WL100 %>% 
  group_by(F.method, R.method, Series, Forecast_Horizon) %>% 
  summarise(ME = sum(ME)/1e3) %>%
  filter(Forecast_Horizon == 1) %>% 
  group_by(F.method,R.method) %>% 
  summarise(AME=sum(abs(ME))) %>% 
  ungroup() -> Avg_BoxCox_WL100_ME_h1_new

# Make everything percentage improvement
Avg_BoxCox_WL100_ME_h1 <- Avg_BoxCox_WL100_ME_h1 %>% 
  mutate(ME=ME/Avg_BoxCox_WL100_ME_h1[1,]$ME)

Avg_BoxCox_WL100_ME_h1_new <- Avg_BoxCox_WL100_ME_h1_new %>%
  mutate(AME=AME/Avg_BoxCox_WL100_ME_h1_new[1,]$AME)


Avg_BoxCox_WL100_ME_h1 %>% 
  mutate(F.method = recode(F.method, Unbiased_M1 = "Unbiased (Method 1)", 
                           Unbiased_M2 = "Unbiased (Method 2)")) %>% 
  spread(key = F.method, value = ME) %>% 
  kable(format = "latex",digits = 2)

print("New ME")
Avg_BoxCox_WL100_ME_h1_new %>% 
  mutate(F.method = recode(F.method, Unbiased_M1 = "Unbiased (Method 1)", 
                           Unbiased_M2 = "Unbiased (Method 2)")) %>% 
  spread(key = F.method, value = AME) %>% 
  kable(format = "latex",digits = 2)

print("MSE")
DF_BoxCoxTrans_WL100 %>% 
  group_by(`F.method`, `R.method`, Forecast_Horizon) %>% 
  summarise(MSE = round(mean(SquaredE)/1e3, digits = 2)) %>% 
  filter(Forecast_Horizon == 1) %>% 
  ungroup() %>% 
  dplyr::select(-Forecast_Horizon)-> Avg_BoxCox_WL100_MSE_h1

Avg_BoxCox_WL100_MSE_h1 <- Avg_BoxCox_WL100_MSE_h1 %>%
  mutate(MSE=MSE/Avg_BoxCox_WL100_MSE_h1[1,]$MSE)

Avg_BoxCox_WL100_MSE_h1 %>% 
  mutate(F.method = recode(F.method, Unbiased_M1 = "Unbiased (Method 1)", 
                           Unbiased_M2 = "Unbiased (Method 2)")) %>% 
  spread(key = F.method, value = MSE) %>% 
  kable(format = "latex", digits = 2)

```
