---
title: "Tourism Data Analysis"
output:
  pdf_document: 
    keep_tex: yes
  html_document: default
date: "31 July 2019"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

library(tidyverse)
library(fpp2)
library(Matrix)
library(hts)
library(readr)
library(BigVAR)
library(vars)
library(tibble)
library(kableExtra)
library(reshape2)
```

# BoxCox Transformation

```{r, echo=FALSE}
DF_BoxCoxTrans <- read.csv("DF_BoxCoxTrans.csv")[,-1]

DF_BoxCoxTrans %>% mutate(SquaredE = (`Actual` - `Forecasts`)^2) -> DF_BoxCoxTrans

DF_BoxCoxTrans %>% 
  group_by(`F.method`, `R.method`, Forecast_Horizon) %>% 
  summarise(MSE = round(mean(SquaredE)/1e3, digits = 2)) %>% 
  filter(Forecast_Horizon == 1) %>% 
  ungroup() %>% 
  dplyr::select(-Forecast_Horizon)-> Avg_BoxCox_MSE_h1

Avg_BoxCox_MSE_h1 %>% 
  mutate(F.method = recode(F.method, Unbiased_M1 = "Unbiased (Method 1)", 
                           Unbiased_M2 = "Unbiased (Method 2)")) %>% 
  spread(key = F.method, value = MSE) %>% 
  kable(format = "latex")
  
```

# More analysis on BoxCox transformed resulst

```{r}
DF_BoxCoxTrans %>% 
  group_by(`F.method`, `R.method`, Forecast_Horizon, Series) %>% 
  summarise(MSE = round(mean(SquaredE)/1e3, digits = 2)) %>% 
  filter(R.method == "Base", Forecast_Horizon == 1, 
         F.method %in%c("Bias","Unbiased_M1")) %>% 
  ungroup() %>% 
  dplyr::select(-R.method, -Forecast_Horizon) %>% 
  spread(key = F.method, value = MSE) %>% 
  mutate("Bias-Unbiase" = Bias - Unbiased_M1) %>% 
  filter(`Bias-Unbiase` < -5)



```
Bias correction is giving wiered results for `Total` series. 

```{r echo=FALSE}
DF_BoxCoxTrans %>% 
  filter(Forecast_Horizon == 1, Series == "Total") -> DF_BoxCoxTrans_Tot_h1

# DF_BoxCoxTrans_h1 %>% 
#   filter(Series == "Total", R.method == "Base", F.method == "Bias") %>% 
#   dplyr::select(Actual, Replication) -> Total_BoxCox_True
  
  
DF_BoxCoxTrans_Tot_h1 %>% 
  filter(R.method == "Base", F.method %in%c("Bias","Unbiased_M1")) %>%
  ungroup() %>% 
  dplyr::select(F.method, Forecasts, Actual, Replication) %>% 
  spread(key = F.method, value = Forecasts) %>% 
  gather(-Replication, key = "Forecasts/Actual", value = Val) -> DF_BoxCoxTrans_Tot_h1
  
DF_BoxCoxTrans_Tot_h1 %>% 
  mutate(`Forecasts/Actual` = recode(`Forecasts/Actual`, "Unbiased_M1" = "Unbiased")) %>%   ggplot() + 
  geom_line(aes(x = Replication, y = Val, color = `Forecasts/Actual`)) + 
  ylab("Forecasts/Actual") + 
  ggtitle("Forecasts follow from BoxCox Transformation") + 
  theme(legend.position="bottom") 
  
  


```


```{r}
OvernightTrips_Region <- read_csv("OvernightTrips_2017.csv")[,-(1:3)]

## Replacing the odd value in `Adelaide Hills` with the average of its adjecent numbers ##

OvernightTrips_Region %>% 
  dplyr::select(`Adelaide Hills`) %>% 
  filter(`Adelaide Hills` > 80) %>% 
  as.numeric() -> a

which(OvernightTrips_Region$`Adelaide Hills`==a) -> x

OvernightTrips_Region %>% 
  dplyr::select(`Adelaide Hills`) %>% 
  filter(row_number() %in% c(60+12,60-12)) %>% 
  summarise(mean(`Adelaide Hills`)) %>% 
  as.numeric() -> b

OvernightTrips_Region_new <- OvernightTrips_Region %>% 
  mutate(`Adelaide Hills` = case_when(`Adelaide Hills`%% a == 0 ~ b, 
                                      TRUE ~ as.double(`Adelaide Hills`)))

#generating the hierarchy
#Hierarchy<-suppressMessages(hts(Bottom_level, list(7, c(14,21,12,12,5,5,7))))
Hierarchy <- suppressMessages(hts(OvernightTrips_Region_new, 
                                  list(7, c(6,5,4,4,3,3,2), c(2,2,1,4,4,1,3,1,3,6,7,3,4,3,2,3,3,4,2,3,1,1,1,2,2,3,4))))

AllTS_new <- allts(Hierarchy) %>%
  as_tibble()

lambda <- numeric()

for (j in 1:140) {#C=140
  
  Train <- AllTS_new[j:(100+j-1), "Total"] %>% as.ts()

  lambda[j] <- BoxCox.lambda(Train)
  
  
}
```


# Log Transformation

```{r, echo=FALSE}
DF_LogTrans <- read.csv("DF_LogTrans.csv")[,-1]

DF_LogTrans %>% mutate(SquaredE = (`Actual` - `Forecasts`)^2) -> DF_LogTrans

DF_LogTrans %>% 
  group_by(`F.method`, `R.method`, Forecast_Horizon) %>% 
  summarise(MSE = round(mean(SquaredE)/1e3, digits = 2)) %>% 
  filter(Forecast_Horizon == 1) %>% 
  ungroup() %>% 
  dplyr::select(-Forecast_Horizon)-> Avg_Log_MSE_h1

Avg_Log_MSE_h1 %>% 
  mutate(F.method = recode(F.method, Unbiased_M1 = "Unbiased (Method 1)", 
                           Unbiased_M2 = "Unbiased (Method 2)")) %>% 
  spread(key = F.method, value = MSE) %>% 
  kable(format = "latex")
  
```


```{r echo=FALSE}
DF_LogTrans %>% 
  filter(Forecast_Horizon == 1) -> DF_LogTrans_h1

DF_LogTrans_h1 %>% 
  filter(Series == "Total", R.method == "Base", F.method == "Bias") %>% 
  dplyr::select(Actual, Replication) -> Total_Log_True
  
  
DF_LogTrans_h1 %>% 
  filter(Series == "Total", R.method == "Base", F.method %in%c("Bias","Unbiased_M1")) -> Total_Log_Fc


ggplot() + 
  geom_line(data = Total_Log_Fc, aes(x = Replication, y = Forecasts, color = `F.method`)) + 
  geom_line(data = Total_Log_True, mapping = aes(x = Replication, y = Actual)) + 
  ylab("Forecasts/Actual") + 
  ggtitle("Forecasts follows from Log Transformation")
  
  


```


```{r, echo=FALSE}

DF_MSE <- DF_LogTrans %>% 
  mutate(SquaredE = (`Actual` - `Forecasts`)^2) %>% 
  filter(`Forecast_Horizon` == 1) %>% 
  dplyr::select(-`Forecast_Horizon`) %>% 
  group_by(`F.method`, `R.method`, Replication) %>% 
  summarise(MSE = mean(SquaredE)) 


DF_MSE %>% 
  filter(`F.method`=="Unbiased_M1", `R.method`%in% c("Base", "OLS", "MinT(Shrink)", "WLS")) %>% 
  spread(key = `R.method`, value = MSE) %>% 
  mutate("Base-OLS" = Base - OLS,
         "Base-MinT" = Base - `MinT(Shrink)`,
         "Base-WLS" = Base - WLS) %>% 
  dplyr::select(Replication, `Base-OLS`, `Base-MinT`, `Base-WLS`) %>%
  rename("OLS" = "Base-OLS", "MinT" = "Base-MinT", "WLS" = "Base-WLS") %>% 
  gather(`OLS`, `WLS`, `MinT`,  key = Method, value = MSE) %>% 
  mutate(Method = factor(Method, levels = c("OLS", "MinT", "WLS"))) %>% 
  ggplot(aes(x = Method, y = MSE)) + 
  geom_boxplot() + 
  ylab("MSE") + xlab("Reconciliation Method")

```

